# Generated by Django 6.0.4 on 2026-04-18 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('architecture', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('Sales Order', 'Sales Order'), ('Architecture Request', 'Architecture Request')], default='Sales Order', max_length=25)),
                ('driver_name', models.CharField(help_text='Name of driver (stored as text so history is preserved even if the user account is later changed)', max_length=150)),
                ('delivery_team', models.CharField(choices=[('Mitra', 'Mitra (own team)'), ('Manufacturer', 'Manufacturer / Supplier delivery'), ('Third-party', 'Third-party courier')], default='Mitra', max_length=20)),
                ('vehicle_plate', models.CharField(blank=True, help_text='Truck or vehicle plate number', max_length=20)),
                ('schedule_date', models.DateField(help_text='Planned delivery date')),
                ('start_location', models.CharField(default='Mitra Planners and Builders — Main Warehouse', help_text='Origin address (hub or warehouse)', max_length=200)),
                ('end_location', models.CharField(help_text='Delivery destination (hardware store or project site)', max_length=200)),
                ('route_notes', models.TextField(blank=True, help_text='Directions, landmarks, or routing instructions')),
                ('weather_delay', models.BooleanField(default=False, help_text='True if rain or weather prevented / delayed delivery')),
                ('driver_unavailable_delay', models.BooleanField(default=False, help_text='True if the assigned driver was unavailable')),
                ('closed_store_delay', models.BooleanField(default=False, help_text='True if the destination was closed on arrival')),
                ('delay_remarks', models.TextField(blank=True, help_text='Free-text explanation of any delays')),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Out for Delivery', 'Out for Delivery'), ('Arrived', 'Arrived'), ('Received', 'Received'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='Timestamp when status moved to Received', null=True)),
                ('received_by', models.CharField(blank=True, help_text='Name of person who signed / received the delivery', max_length=150)),
                ('dr_number', models.CharField(blank=True, help_text='Delivery Receipt number issued upon completion', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Any additional delivery notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_created', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, help_text='Mitra driver assigned to this trip', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_as_driver', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, help_text='Set if delivering a Sales Order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='sales.order')),
                ('request', models.ForeignKey(blank=True, help_text='Set if delivering an Architecture Material Request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='architecture.materialrequest')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-schedule_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_status_changes', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='delivery.delivery')),
            ],
            options={
                'verbose_name': 'Delivery Status Log',
                'verbose_name_plural': 'Delivery Status Logs',
                'ordering': ['changed_at'],
            },
        ),
    ]
