# Generated by Django 6.0.4 on 2026-04-14 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='e.g., Construction Chemicals, Paints & Coatings', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of what belongs in this category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('supplier_type', models.CharField(choices=[('Manufacturer', 'Manufacturer'), ('External', 'External')], default='External', help_text='Manufacturer = Magna Prime; External = Architecture suppliers', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as True for Magna Prime — the main manufacturer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, help_text='Optional: product code or barcode for quick lookup', max_length=50, null=True, unique=True)),
                ('name', models.CharField(help_text='e.g., Buildrite Waterproofing 20kg, Sinclair Permacoat 4L White', max_length=200)),
                ('unit', models.CharField(choices=[('bag', 'Bag'), ('pcs', 'Pieces'), ('liters', 'Liters'), ('kg', 'Kilograms'), ('gallons', 'Gallons'), ('rolls', 'Rolls'), ('boxes', 'Boxes'), ('sets', 'Sets'), ('drums', 'Drums'), ('tubes', 'Tubes'), ('sheets', 'Sheets'), ('lengths', 'Lengths')], max_length=20)),
                ('current_cost', models.DecimalField(decimal_places=2, help_text='Buying price from Magna Prime or supplier', max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Price charged to hardware stores or clients', max_digits=10)),
                ('is_sales_inventory', models.BooleanField(default=True, help_text='Check if this product is stocked in the Sales warehouse')),
                ('reorder_level', models.IntegerField(default=10, help_text='Show low-stock alert when stock falls below this number')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide material without deleting historical records')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='materials.category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='materials.supplier')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'ordering': ['name'],
            },
        ),
    ]
