# Generated by Django 6.0.4 on 2026-04-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, help_text='Short product description, highlights, or usage notes'),
        ),
        migrations.AddField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional product photo to show in the catalog', null=True, upload_to='products/'),
        ),
    ]
