# Generated by Django 6.0.4 on 2026-04-14 09:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(choices=[('Admin', 'Admin'), ('Sales', 'Sales'), ('Architect', 'Architect'), ('Warehouse', 'Warehouse'), ('Driver', 'Driver')], help_text='The name of this role', max_length=50, unique=True)),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='JSON object of permissions, e.g. {"can_approve_orders": true}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['role_name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('fullname', models.CharField(help_text="Employee's full name", max_length=150)),
                ('department', models.CharField(choices=[('Sales', 'Sales'), ('Architecture', 'Architecture'), ('Warehouse', 'Warehouse'), ('Logistics', 'Logistics'), ('Management', 'Management')], default='Sales', max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, help_text='Role assigned by Admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.role')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('CREATE_USER', 'Created User Account'), ('CREATE_ORDER', 'Created Sales Order'), ('UPDATE_ORDER', 'Updated Sales Order'), ('CREATE_MATERIAL_REQUEST', 'Created Material Request'), ('UPDATE_INVENTORY', 'Updated Inventory'), ('CREATE_PROCUREMENT', 'Created Procurement Order'), ('UPDATE_DELIVERY', 'Updated Delivery Status'), ('CREATE_PROJECT', 'Created Project'), ('APPROVE', 'Approved Record'), ('DELETE', 'Deleted Record'), ('OTHER', 'Other Action')], max_length=50)),
                ('table_affected', models.CharField(blank=True, help_text='e.g. orders, inventory, material_requests', max_length=100)),
                ('record_id', models.IntegerField(blank=True, help_text='e.g. order_id=105', null=True)),
                ('description', models.TextField(blank=True, help_text='e.g. "Sales Juan created order for Buildrite Hardware"')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user at time of action', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction Log',
                'verbose_name_plural': 'Transaction Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
