# Generated by Django 6.0.4 on 2026-04-15 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0002_material_description_material_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, help_text='Current quantity on hand. Updated automatically on each transaction.')),
                ('warehouse_location', models.CharField(blank=True, default='Main Warehouse', max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='materials.material')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventory',
                'ordering': ['material__name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER', 'Transfer')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Always positive. The direction is determined by transaction_type.')),
                ('quantity_before', models.IntegerField(help_text='Stock quantity before this transaction was applied.')),
                ('quantity_after', models.IntegerField(help_text='Stock quantity after this transaction was applied.')),
                ('reference_type', models.CharField(choices=[('MANUAL', 'Manual Entry'), ('SALES_ORDER', 'Sales Order'), ('ARCH_REQUEST', 'Architecture Request'), ('PROCUREMENT', 'Procurement Order'), ('ADJUSTMENT', 'Stock Adjustment'), ('INITIAL', 'Initial Stock'), ('RETURN', 'Return / Reversal')], default='MANUAL', max_length=30)),
                ('reference_id', models.IntegerField(blank=True, help_text='The PK of the related document (order_id, procurement_id, etc.)', null=True)),
                ('remarks', models.TextField(blank=True, help_text='e.g., "Received from Magna Prime DR#1234", "Issued for Project Lucena Renovation"')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp is set automatically when the transaction is saved.')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='materials.material')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory Transaction',
                'verbose_name_plural': 'Inventory Transactions',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
