# Generated by Django 6.0.4 on 2026-04-18 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0002_material_description_material_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BOQHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1, help_text='Incremented each time a revised BOQ is created')),
                ('total_estimate', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all BOQ item totals. Recalculated on save.', max_digits=14)),
                ('is_final', models.BooleanField(default=False, help_text='Mark True when this BOQ version is approved and in use')),
                ('notes', models.TextField(blank=True, help_text='Revision notes — what changed from the previous version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boqs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BOQ',
                'verbose_name_plural': 'BOQs',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='BOQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_qty', models.DecimalField(decimal_places=2, help_text='Estimated quantity needed for this project', max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Estimated cost per unit at time of BOQ creation', max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='required_qty × unit_cost — calculated automatically', max_digits=12)),
                ('source_type', models.CharField(choices=[('Sales Inventory', 'Sales Inventory (Mitra Warehouse)'), ('External', 'External Supplier')], default='Sales Inventory', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('boq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='architecture.boqheader')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boq_items', to='materials.material')),
                ('supplier', models.ForeignKey(blank=True, help_text='External supplier (only if source_type = External)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boq_items', to='materials.supplier')),
            ],
            options={
                'verbose_name': 'BOQ Item',
                'verbose_name_plural': 'BOQ Items',
            },
        ),
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all item subtotals. Recalculated on save.', max_digits=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Partially Fulfilled', 'Partially Fulfilled'), ('Fulfilled', 'Fulfilled'), ('Rejected', 'Rejected')], default='Pending', max_length=25)),
                ('fulfillment_source', models.CharField(choices=[('Sales Inventory', 'Sales Inventory'), ('External', 'External Supplier'), ('Mixed', 'Mixed Sources')], default='Sales Inventory', max_length=20)),
                ('stock_deducted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes from Admin when approving or rejecting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('architect', models.ForeignKey(help_text='Architect who submitted this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material Request',
                'verbose_name_plural': 'Material Requests',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fulfilled_qty', models.DecimalField(decimal_places=2, default=0, help_text='How much was actually issued from the warehouse', max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='required_qty × unit_cost — calculated automatically', max_digits=12)),
                ('source_type', models.CharField(choices=[('Sales Inventory', 'Sales Inventory'), ('External', 'External Supplier')], default='Sales Inventory', max_length=20)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_request_items', to='materials.material')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_items', to='architecture.materialrequest')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_request_items', to='materials.supplier')),
            ],
            options={
                'verbose_name': 'Material Request Item',
                'verbose_name_plural': 'Material Request Items',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text="Short descriptive name, e.g., 'Lucena Residential Renovation'", max_length=200)),
                ('client_name', models.CharField(help_text='Name of the project owner or client', max_length=200)),
                ('location', models.TextField(help_text='Full project site address within Quezon Province')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('Ongoing', 'Ongoing'), ('On Hold', 'On Hold'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Planning', max_length=20)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated total project budget in PHP', max_digits=14, null=True)),
                ('description', models.TextField(blank=True, help_text='Project scope, special notes, or instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('architect', models.ForeignKey(help_text='Architect responsible for this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_requests', to='architecture.project'),
        ),
        migrations.AddField(
            model_name='boqheader',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boqs', to='architecture.project'),
        ),
        migrations.AlterUniqueTogether(
            name='boqheader',
            unique_together={('project', 'version')},
        ),
    ]
