# Generated by Django 6.0.4 on 2026-04-19 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0002_material_description_material_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('expected_delivery_date', models.DateField(blank=True, help_text='Date supplier is expected to deliver (usually 5–7 days)', null=True)),
                ('actual_delivery_date', models.DateField(blank=True, help_text='Date goods actually arrived at the warehouse', null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all item subtotals. Recalculated automatically.', max_digits=14)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Confirmed', 'Confirmed'), ('Shipped', 'Shipped'), ('Received', 'Received'), ('Cancelled', 'Cancelled')], default='Draft', max_length=15)),
                ('order_method', models.CharField(choices=[('Email', 'Email'), ('Phone', 'Phone Call'), ('Website', 'Supplier Website'), ('In-person', 'In-person / Walk-in')], default='Email', max_length=15)),
                ('dr_number', models.CharField(blank=True, help_text='Delivery Receipt number from the supplier', max_length=50)),
                ('stock_received', models.BooleanField(default=False, help_text='True once inventory has been updated for this PO')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who confirmed / approved this PO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_procurements', to=settings.AUTH_USER_MODEL)),
                ('ordered_by', models.ForeignKey(help_text='Warehouse staff who created this PO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_orders', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(help_text='Supplier this order is placed with (usually Magna Prime)', on_delete=django.db.models.deletion.PROTECT, related_name='procurement_orders', to='materials.supplier')),
            ],
            options={
                'verbose_name': 'Procurement Order',
                'verbose_name_plural': 'Procurement Orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_qty', models.IntegerField(help_text='Quantity ordered from supplier')),
                ('received_qty', models.IntegerField(default=0, help_text='Quantity actually received — filled in when marking PO as Received')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Cost per unit from the supplier — snapshot at time of ordering', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='ordered_qty × unit_cost — calculated automatically', max_digits=12)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_items', to='materials.material')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.procurementorder')),
            ],
            options={
                'verbose_name': 'Procurement Item',
                'verbose_name_plural': 'Procurement Items',
            },
        ),
    ]
