# Generated by Django 6.0.4 on 2026-04-17 04:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0002_material_description_material_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('client_type', models.CharField(choices=[('Hardware Store', 'Hardware Store'), ('Walk-in', 'Walk-in Customer'), ('Contractor', 'Contractor')], default='Hardware Store', max_length=20)),
                ('delivery_zone', models.CharField(choices=[('North Quezon', 'North Quezon'), ('Central Quezon', 'Central Quezon'), ('South Quezon', 'South Quezon'), ('Lucena City', 'Lucena City'), ('Pick-up', 'Pick-up / No Delivery')], default='Pick-up', help_text='Used for delivery routing in Phase 6', max_length=30)),
                ('notes', models.TextField(blank=True, help_text='Any special instructions, credit terms, or preferences')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['client_name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all order item subtotals. Recalculated on save.', max_digits=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Preparing', 'Preparing'), ('Out for Delivery', 'Out for Delivery'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Partial', 'Partial'), ('Paid', 'Paid')], default='Unpaid', max_length=10)),
                ('order_type', models.CharField(choices=[('Regular', 'Regular'), ('Preorder', 'Pre-order'), ('Bulk', 'Bulk Order')], default='Regular', max_length=10)),
                ('stock_deducted', models.BooleanField(default=False, help_text='True once inventory has been deducted for this order.')),
                ('notes', models.TextField(blank=True, help_text='Special instructions or delivery notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='sales.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Must be at least 1', validators=[django.core.validators.MinValueValidator(1)])),
                ('price_at_sale', models.DecimalField(decimal_places=2, help_text='Selling price at the time of this order — preserved for history', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='quantity × price_at_sale — calculated automatically', max_digits=12)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='materials.material')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
